### ISSUE TITLE
server.c - baud rates greater than 38400 cause a segmentation fault

### ISSUE THREAD

**Issue by AK6DN** [drovak/os8diskserver#1]
Using baud rates greater than 38400 in the OS8 disk server configuration file cause the server to seg fault. The reason is because the baud rate value (B50, B75, ...) is used as the index into a structure to print out the baud rate. But there in a discontinuity in the index between B38400 and B57600. The problem is in config.c and the baud_val it returns.

Here is the relevant portion of the termios.h include file:

/\* cflag bits */

/\* Baud rate values.  These must fit in speed_t, which is unsigned
   char.  See also the extended baud rates below.  These baud rates
   set an additional bit. */
# define CBAUD    0x0100f
# define B0       0x00000
# define B50      0x00001
# define B75      0x00002
# define B110     0x00003
# define B134     0x00004
# define B150     0x00005
# define B200     0x00006
# define B300     0x00007
# define B600     0x00008
# define B1200    0x00009
# define B1800    0x0000a
# define B2400    0x0000b
# define B4800    0x0000c
# define B9600    0x0000d
# define B19200   0x0000e
# define B38400   0x0000f
# define CSIZE    0x00030
# define CS5      0x00000
# define CS6      0x00010
# define CS7      0x00020
# define CS8      0x00030
# define CSTOPB   0x00040
# define CREAD    0x00080
# define PARENB   0x00100
# define PARODD   0x00200
# define HUPCL    0x00400
# define CLOCAL   0x00800

/\* Extended baud rates above 37K. */
# define CBAUDEX  0x0100f
# define B57600   0x01001
# define B115200  0x01002
# define B128000  0x01003
# define B230400  0x01004
# define B256000  0x01005
# define B460800  0x01006
# define B500000  0x01007
# define B576000  0x01008
# define B921600  0x01009
# define B1000000 0x0100a
# define B1152000 0x0100b
# define B1500000 0x0100c
# define B2000000 0x0100d
# define B2500000 0x0100e
# define B3000000 0x0100f

**Comment by vrs42** [comment]
I was able to reproduce and (I think) fix this.  I generated a pull request for the fix.

**Comment by vrs42** [comment]
Fix has been merged in.
