### ISSUE TITLE
Interrupts aren't disabled and cause issues with FORTRAN

### ISSUE THREAD

**Issue by drovak** [drovak/os8diskserver#3]
David Gesswein mentions that running a short program to disable the serial card's interrupt before starting OS/8 solves this problem. Adding this to the handler code should be trivial.
        *200
        PKIE=6405
        CLL CLA
        PKIE            /CLEAR INTERRUPT
        JMP I (7605
        $

**Comment by vrs42** [comment]
This should be fixed in the current version.
